version: '3.4'

services:
  migrations:
    build:
      context: ../../
      dockerfile: templates/service/database/Dockerfile
    depends_on:
      - sqlserver
    environment:
      - IdentityServer_DB=SharedLocker_Identity
      - SharedLocker_DB=SharedLocker_ModuleDb
      - SA_PASSWORD=yourStrong(!)Password
